name: Continuous

on:
  pull_request:
    branches:
    - '*'

env:
  version: 1.2.3

jobs:

  SecretTest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Change the ReleaseNotes
      shell: bash
      run: |
        echo "Changing the release notes...."
        echo "I am a new line." >> ReleaseNotes.md
    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        base: main
        add-paths: ReleaseNotes.md
        delete-branch: true
        branch: automation/update-current-release-to-${{ env.version }}
        title: Update website release info (v${{ env.version}})
        reviewers: trisyoungs
